services:
  # Cục 1: Redis dùng để lưu Sổ Lệnh
  redis:
    image: redis:alpine
    container_name: cryptoex_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  # Cục 2: MySQL (bằng Docker)
  mysql:
    image: mysql:8.0
    container_name: cryptoex_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root        # Đặt cứng pass là root luôn (khỏi quên)
      MYSQL_DATABASE: cryptoex         # Tự động tạo sẵn CSDL tên cryptoex luôn!
    ports:
      - "3310:3306"                    # CHÚ Ý: Bên ngoài ta gọi cổng 3310, chạy vô 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
